server {
    listen 80;
    server_name ${COMPOSE_PROJECT_NAME}.local.harborn.com;
    root /var/www/html/web;
    index index.php index.html;
    client_max_body_size 64M;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|webp|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform, immutable";
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_read_timeout 300;
    }

    location ~ /\. {
        deny all;
    }

    location ~* /(wp-config\.php|wp-cli\.yml|php\.ini|\.log)$ {
        deny all;
    }

    location ~* /xmlrpc.php$ {
         deny all;
         access_log off;
         log_not_found off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location ~* /(sitemap\.xml|sitemap_index\.xml|wp-content/uploads/.*\.xml)$ {
        allow all;
        log_not_found off;
        access_log off;
    }
}