# services:
#   nginx:
#     image: nginx:stable-alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./docker-resources/nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - .:/var/www/html
#     depends_on:
#       - php-fpm

#   php-fpm:
#     build:
#       target: php
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/var/www/html

version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./web:/var/www/html
      - ./vendor:/var/www/vendor
      - ./docker-resources/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    volumes:
    - ./web:/var/www/html
    - ./vendor:/var/www/vendor