name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, pdo_mysql, dom, curl, json, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Configure PHP_CodeSniffer (set installed_paths for WPCS)
        run: ./vendor/bin/phpcs --config-set installed_paths ./vendor/wp-coding-standards/wpcs

      - name: Lint PHP with PHP_CodeSniffer
        run: composer run phpcs

      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Pnpm theme dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: ./web/app/themes/harborn

      - name: Lint JavaScript
        run: pnpm lint
        working-directory: ./web/app/themes/harborn

      - name: Run Codeception tests
        run: ./vendor/bin/codecept run --no-interaction --coverage --coverage-xml